# Generated by Django 2.2.6 on 2019-11-16 09:00
import json
import os

from django.db import migrations, models
from datetime import datetime


def fulling_events(apps, schema_editor):
    filename = os.path.dirname(os.path.abspath(__file__)) + '/all_events.json'
    data = json.loads(open(filename, 'r').read())
    Event = apps.get_model('events', 'Event')

    for event in data:
        year, month, day = event['start_date'].split('T')[0].split('-')

        image_url = event['image']['original'] if event['image'] else ''

        Event.objects.create(
            x = event['coords'][0],
            y = event['coords'][1],
            region_id = event['region_id'],
            address = event['address'],
            description = event['description'],
            name = event['name'],
            slug = event['slug'],
            image_url = image_url,
            date = datetime(int(year), int(month), int(day)),
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=6, max_digits=9)),
                ('y', models.DecimalField(decimal_places=6, max_digits=9)),
                ('region_id', models.IntegerField()),
                ('address', models.TextField(verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('name', models.TextField(verbose_name='Имя')),
                ('slug', models.TextField()),
                ('image_url', models.TextField(verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.RunPython(fulling_events, migrations.RunPython.noop),
    ]
