# Generated by Django 2.2 on 2019-07-19 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Текст уведомления')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('type', models.CharField(choices=[('N', 'Уведомление'), ('S', 'Успешное'), ('W', 'Предупреждение'), ('C', 'Критическое')], default='N', max_length=1, verbose_name='Тип')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_purpose_user', to=settings.AUTH_USER_MODEL, verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'default_permissions': (),
            },
        ),
    ]
