# Generated by Django 2.2.6 on 2019-10-08 17:59

import backend.blog.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks
import wagtailmarkdownblock.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191008_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('recipe', wagtail.snippets.blocks.SnippetChooserBlock(backend.blog.models.Recipe)), ('code', wagtailmarkdownblock.blocks.MarkdownBlock())]),
        ),
    ]
