# Generated by Django 2.2.6 on 2019-10-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0005_auto_20191008_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='head_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
