# Generated by Django 2.2.6 on 2019-10-24 07:28

import backend.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backend.users.managers.UserManager()),
            ],
        ),
    ]
