# Generated by Django 2.2.6 on 2019-11-03 11:24

import backend.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=backend.users.utils.avatar_directory_path, verbose_name='Аватар'),
        ),
    ]
